const translations = {
    es: {
        // Navegación
        navInicio: "Inicio",
        navProyectos: "Proyectos",
        navHabilidades: "Habilidades",
        navContacto: "Contacto",
        // Hero Section
        heroTitle: "Hola, soy Jesús Millán,<br>Desarrollador Full-Stack.",
        heroSubtitle: "Creo soluciones web de alto impacto que impulsan el crecimiento de tu negocio.",
        heroButton: "Ver Mis Proyectos",
        // Proyectos
        proyectosTitle: "Proyectos Destacados",
        proyectosSubtitle: "Casos de éxito donde la tecnología se transformó en eficiencia, ahorro y crecimiento para mis clientes.",
        project1Title: "Plataforma de Auditorías en Tiempo Real",
        project1Desc: "Aplicación web para optimizar la programación y ejecución de auditorías internas, entregando indicadores a la dirección el mismo día.",
        project2Title: "Plataforma de QA para Ventas de Seguros",
        project2Desc: "Sistema web para auditar llamadas de ventas, automatizando alertas críticas y generando reportes de efectividad para la gerencia.",
        project3Title: "Mantenimiento Evolutivo de ERP Gubernamental",
        project3Desc: "Responsable de la corrección de bugs y adaptación de flujos de trabajo en un sistema monolítico a gran escala para una entidad de control fiscal.",
        project4Title: "Demo en Vivo: CRUD con Supabase",
        project4Desc: "Proyecto demostrativo para ilustrar una arquitectura full-stack. La aplicación realiza operaciones CRUD en tiempo real, mostrando los datos en una tabla interactiva.",
        project4Link: "Ver Demo en Vivo →",
        // Habilidades
        skillsTitle: "De la Idea al Lanzamiento",
        skillsSubtitle: "Más que un programador, soy un socio tecnológico. Mi objetivo es acompañarte en cada fase del proyecto para convertir tu visión en una realidad digital exitosa.",
        skillCard1Title: "1. Estrategia y Diseño",
        skillCard1Desc: "Todo gran producto empieza con un plan sólido. Te ayudo a definir la estructura y la experiencia de usuario para sentar las bases del éxito.",
        skillPillUX: "UX/UI Prototyping",
        skillPillArch: "Arquitectura de Software",
        skillCard2Title: "2. Desarrollo Frontend",
        skillCard2Desc: "Construyo interfaces rápidas, interactivas y accesibles que tus usuarios amarán, totalmente adaptadas a cualquier dispositivo.",
        skillCard3Title: "3. Backend y Datos",
        skillCard3Desc: "Desarrollo la lógica de negocio y las bases de datos seguras y escalables que dan vida a la aplicación y protegen tu información.",
        // Contacto
        contactTitle: "Contacto",
        contactSubtitle: "Hablemos. Estoy disponible para nuevos proyectos y oportunidades.",
        contactButton: "Envíame un Email",
        contactButtonWP: "Escríbeme en WhatsApp",
        whatsappMessage: "Hola, vi tu portfolio y me gustaría conversar.",
        // footer
        footerEmail: "Email: millanqjesus@gmail.com",
        footerCNPJ: "CNPJ: 62.019.664/0001-50",
        footerRights: "© 2025 Jesús Millán. Todos los derechos reservados.",
    },
    pt: {
        navInicio: "Início",
        navProyectos: "Projetos",
        navHabilidades: "Habilidades",
        navContacto: "Contato",
        heroTitle: "Olá, eu sou Jesús Millán,<br>Desenvolvedor Full-Stack.",
        heroSubtitle: "Crio soluções web de alto impacto que impulsionam o crescimento do seu negócio.",
        heroButton: "Ver Meus Projetos",
        proyectosTitle: "Projetos em Destaque",
        proyectosSubtitle: "Casos de sucesso onde a tecnologia se transformou em eficiência, economia e crescimento para meus clientes.",
        project1Title: "Plataforma de Auditorias em Tempo Real",
        project1Desc: "Aplicação web para otimizar o agendamento e a execução de auditorias internas, entregando indicadores à gerência no mesmo dia.",
        project2Title: "Plataforma de QA para Vendas de Seguros",
        project2Desc: "Sistema web para auditar chamadas de vendas, automatizando alertas críticos e gerando relatórios de eficácia para a gerência.",
        project3Title: "Manutenção Evolutiva de ERP Governamental",
        project3Desc: "Responsável pela correção de bugs e adaptação de fluxos de trabalho em um sistema monolítico de grande escala para uma entidade de controle fiscal.",
        project4Title: "Demo ao Vivo: CRUD com Supabase",
        project4Desc: "Projeto de demonstração para ilustrar uma arquitetura full-stack. A aplicação realiza operações CRUD em tempo real, exibindo os dados em uma tabela interativa.",
        project4Link: "Ver Demo ao Vivo →",
        skillsTitle: "Da Ideia ao Lançamento",
        skillsSubtitle: "Mais que um programador, sou um parceiro de tecnologia. Meu objetivo é acompanhar você em cada fase do projeto para transformar sua visão em uma realidade digital de sucesso.",
        skillCard1Title: "1. Estratégia e Design",
        skillCard1Desc: "Todo grande produto começa com um plano sólido. Eu ajudo a definir a estrutura e a experiência do usuário para estabelecer as bases para o sucesso.",
        skillPillUX: "Prototipagem UX/UI",
        skillPillArch: "Arquitetura de Software",
        skillCard2Title: "2. Desenvolvimento Frontend",
        skillCard2Desc: "Construo interfaces rápidas, interativas e acessíveis que seus usuários vão adorar, totalmente adaptadas a qualquer dispositivo.",
        skillCard3Title: "3. Backend e Dados",
        skillCard3Desc: "Desenvolvo a lógica de negócio e os bancos de dados seguros e escaláveis que dão vida à aplicação e protegem suas informações.",
        contactTitle: "Contato",
        contactSubtitle: "Vamos conversar. Estou disponível para novos projetos e oportunidades.",
        contactButton: "Envie-me um E-mail",
        contactButtonWP: "Escreva-me no WhatsApp",
        whatsappMessage: "Olá, vi seu portfólio e gostaria de conversar.",
        footerEmail: "E-mail: millanqjesus@gmail.com",
        footerCNPJ: "CNPJ: 62.019.664/0001-50",
        footerRights: "© 2025 Jesús Millán. Todos os direitos reservados.",
    },
    en: {
        navInicio: "Home",
        navProyectos: "Projects",
        project4Title: "Live Demo: CRUD with Supabase",
        project4Desc: "A proof-of-concept project demonstrating a full-stack architecture. The app performs real-time CRUD operations, displaying data in an interactive table.",
        project4Link: "View Live Demo →",
        skillsTitle: "From Idea to Launch",
        skillsSubtitle: "More than a programmer, I'm a technology partner. My goal is to support you through every phase of the project to turn your vision into a successful digital reality.",
        skillCard1Title: "1. Strategy & Design",
        skillCard1Desc: "Every great product begins with a solid plan. I help define the structure and user experience to lay the foundations for success.",
        skillPillUX: "UX/UI Prototyping",
        skillPillArch: "Software Architecture",
        skillCard2Title: "2. Frontend Development",
        skillCard2Desc: "I build fast, interactive, and accessible interfaces that your users will love, fully adapted to any device.",
        skillCard3Title: "3. Backend & Data",
        skillCard3Desc: "I develop the business logic and secure, scalable databases that bring the application to life and protect your information.",
        contactTitle: "Contact",
        contactSubtitle: "Let's talk. I'm available for new projects and opportunities.",
        contactButton: "Send me an Email",
        contactButtonWP: "Message me on WhatsApp",
        whatsappMessage: "Hello, I saw your portfolio and I'd like to chat.",
        footerEmail: "Email: millanqjesus@gmail.com",
        footerCNPJ: "CNPJ: 62.019.664/0001-50",
        footerRights: "© 2025 Jesús Millán. All rights reserved.",
    }
};